In [1]:
# initial imports
import pandas as pd
import numpy as np
from path import Path
from sklearn import tree
from sklearn.preprocessing import LabelEncoder
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split
from sklearn.metrics import confusion_matrix, accuracy_score, classification_report

In [2]:
# Load data
file_path = Path("Resources/winemag-data_cleaned.csv")
wine_df = pd.read_csv(file_path)
wine_df.head()

points  price  country  designation  province  region_1  variety  winery  \
0    96.0  235.0       12           20         6        24        2      15   
1    96.0  110.0       11           20        26        26        9      15   
2    96.0   90.0       12           20         6        26       19      15   
3    96.0   65.0       12           22        27        46       12      15   
4    95.0   66.0        4           20        31        26        9      15   

   tokens  filtered_tokens        1        2        3        4        5  \
0      60               36   2701.0  16004.0  23236.0  28401.0  33079.0   
1      51               31  11481.0  33140.0  41643.0  46758.0  55709.0   
2      47               30  10077.0  26468.0  32151.0  49402.0  61157.0   
3      62               43   1546.0   4238.0  13171.0  15324.0  16356.0   
4      66               37   1546.0  17161.0  18176.0  31536.0  33140.0   

         6        7        8         9        10  
0  39068.0  45330.0  46582.0   63420.0   66669.0  
1  59455.0  69650.0  79653.0  104662.0  106432.0  
2  64289.0  76272.0  88398.0   99749.0  119775.0  
3  25381.0  33140.0  46758.0   56257.0   67144.0  
4  48479.0  49526.0  65848.0   88378.0   90392.0

In [3]:
# Data types
wine_df.dtypes

points             float64
price              float64
country              int64
designation          int64
province             int64
region_1             int64
variety              int64
winery               int64
tokens               int64
filtered_tokens      int64
1                  float64
2                  float64
3                  float64
4                  float64
5                  float64
6                  float64
7                  float64
8                  float64
9                  float64
10                 float64
dtype: object

In [4]:
# find null values
for column in wine_df.columns:
    print(f"Column {column} has {wine_df[column].isnull().sum()} null values")

Column points has 0 null values
Column price has 0 null values
Column country has 0 null values
Column designation has 0 null values
Column province has 0 null values
Column region_1 has 0 null values
Column variety has 0 null values
Column winery has 0 null values
Column tokens has 0 null values
Column filtered_tokens has 0 null values
Column 1 has 0 null values
Column 2 has 0 null values
Column 3 has 0 null values
Column 4 has 0 null values
Column 5 has 0 null values
Column 6 has 0 null values
Column 7 has 0 null values
Column 8 has 0 null values
Column 9 has 0 null values
Column 10 has 0 null values


In [5]:
#Transform features
wine_df["1"] = wine_df["1"] / 100
wine_df["2"] = wine_df["2"] / 100
wine_df["3"] = wine_df["3"] / 100
wine_df["4"] = wine_df["4"] / 100
wine_df["5"] = wine_df["5"] / 100
wine_df["6"] = wine_df["6"] / 100
wine_df["7"] = wine_df["7"] / 100
wine_df["8"] = wine_df["8"] / 100
wine_df["9"] = wine_df["9"] / 100
wine_df["10"] = wine_df["10"] / 100
wine_df.head()

points  price  country  designation  province  region_1  variety  winery  \
0    96.0  235.0       12           20         6        24        2      15   
1    96.0  110.0       11           20        26        26        9      15   
2    96.0   90.0       12           20         6        26       19      15   
3    96.0   65.0       12           22        27        46       12      15   
4    95.0   66.0        4           20        31        26        9      15   

   tokens  filtered_tokens       1       2       3       4       5       6  \
0      60               36   27.01  160.04  232.36  284.01  330.79  390.68   
1      51               31  114.81  331.40  416.43  467.58  557.09  594.55   
2      47               30  100.77  264.68  321.51  494.02  611.57  642.89   
3      62               43   15.46   42.38  131.71  153.24  163.56  253.81   
4      66               37   15.46  171.61  181.76  315.36  331.40  484.79   

        7       8        9       10  
0  453.30  465.82   634.20   666.69  
1  696.50  796.53  1046.62  1064.32  
2  762.72  883.98   997.49  1197.75  
3  331.40  467.58   562.57   671.44  
4  495.26  658.48   883.78   903.92

In [6]:
# Define the features set.
X = wine_df.copy()
X = X.drop("region_1", axis=1)
X.head()

points  price  country  designation  province  variety  winery  tokens  \
0    96.0  235.0       12           20         6        2      15      60   
1    96.0  110.0       11           20        26        9      15      51   
2    96.0   90.0       12           20         6       19      15      47   
3    96.0   65.0       12           22        27       12      15      62   
4    95.0   66.0        4           20        31        9      15      66   

   filtered_tokens       1       2       3       4       5       6       7  \
0               36   27.01  160.04  232.36  284.01  330.79  390.68  453.30   
1               31  114.81  331.40  416.43  467.58  557.09  594.55  696.50   
2               30  100.77  264.68  321.51  494.02  611.57  642.89  762.72   
3               43   15.46   42.38  131.71  153.24  163.56  253.81  331.40   
4               37   15.46  171.61  181.76  315.36  331.40  484.79  495.26   

        8        9       10  
0  465.82   634.20   666.69  
1  796.53  1046.62  1064.32  
2  883.98   997.49  1197.75  
3  467.58   562.57   671.44  
4  658.48   883.78   903.92

In [7]:
# Define the target set.
y = wine_df["region_1"].values
y[:5]

array([24, 26, 26, 46, 26], dtype=int64)

In [8]:
# Splitting into Train and Test sets
X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=78, train_size=0.80)

In [9]:
print(X_train.shape)
print(X_test.shape)
print(y_train.shape)
print(y_test.shape)

(109737, 19)
(27435, 19)
(109737,)
(27435,)


In [10]:
# Creating StandardScaler instance
scaler = StandardScaler()

In [11]:
# Fitting Standard Scaller
X_scaler = scaler.fit(X_train)

In [12]:
# Scaling data
X_train_scaled = X_scaler.transform(X_train)
X_test_scaled = X_scaler.transform(X_test)

### Fitting the Decision Tree Model

In [13]:
# Creating the decision tree classifier instance
model = tree.DecisionTreeClassifier()

In [14]:
# Fitting the model
model = model.fit(X_train_scaled, y_train)

In [15]:
print(model)

DecisionTreeClassifier()


### Making Predictions Using the Tree Model

In [16]:
# Making predictions using the testing data
predictions = model.predict(X_test_scaled)

### Model Evaluation

In [17]:
# Calculating the confusion matrix
cm = confusion_matrix(y_test, predictions)
cm_df = pd.DataFrame(cm)
    #cm, index=["Actual High", "Actual Low", "Actual Med", "Actual Top Shelf"], columns=["Predicted High", "Predicted Low", "Predicted Med", "Predicted Top Shelf"])

# Calculating the accuracy score
acc_score = accuracy_score(y_test, predictions)

In [18]:
print(cm)

[[122   0   0 ...   0   0   0]
 [  0 240   0 ...   0   0   0]
 [  0   0 103 ...   0   0   0]
 ...
 [  0   0   0 ...  63   0   3]
 [  0   0   0 ...   0 330   0]
 [  0   0   0 ...   7   0 145]]


In [19]:
# Displaying results
print("Confusion Matrix")
display(cm_df)
print(f"Accuracy Score : {acc_score}")
print("Classification Report")
print(classification_report(y_test, predictions))

Confusion Matrix


0    1    2   3    4    5    6    7    8    9   ...   38   39   40   41  \
0   122    0    0   0    0    0    8    3    0    2  ...    0    0    6    1   
1     0  240    0   0    0    0    0    0    0    0  ...    0    0    0    0   
2     0    0  103   0    0    0    0    0    0    0  ...    0    0    0    0   
3     0    0    0  67    0    0    5    7    0    1  ...    0    3    0    0   
4     0    0    0   0  172    0    0    0    0    0  ...    0    0    0    0   
5     0    0    0   0    0  238    0    0    0    0  ...    0    0    0    0   
6     6    0    0   0    0    0  507    5    0   10  ...    0    3   10    7   
7     1    0    0   5    0    0    3  177    0    0  ...    0   16    7    0   
8     0    0    0   0    0    0    0    0  105    0  ...    0    0    0    0   
9     2    0    0   0    0    0    6    2    0  104  ...    0    4    6    2   
10    0    0    0   0    0    0    0    0    0    0  ...    0    0    0    0   
11    0    0    0   0    0    0    0    0    0    0  ...    0    0    0    0   
12    0    0    0   0    0    3    0    0    0    0  ...    0    0    0    0   
13    0    0    0   0    0    0    0    0    0    0  ...    0    0    0    0   
14    0    0    0   0    0    0    0    0    0    0  ...    0    0    0    0   
15    1    0    0   0    0    0    9    1    0    1  ...    0    0    7    5   
16    2    0    0   2    0    0    3    5    0    2  ...    0    5    0    1   
17    0    0    0   0    0    0    0    0    0    0  ...    0    0    0    0   
18    0    0    0   0    0    0    0    0    0    0  ...    0    0    0    0   
19    1    0    0   0    0    0   24    0    0    5  ...    0    0    3    0   
20    0    0    0   0    0    0    0    0    0    0  ...    0    0    0    0   
21    0    0    0   0    0    0    0    0    0    0  ...    0    0    0    0   
22    0    0    0   1    0    0    5    1    0    0  ...    0    0    1    0   
23    0    0    0   0    0    0    0    0    0    0  ...    0    0    0    0   
24   30    0    0   2    0    0   22   18    0    5  ...    0    5   19    6   
25    0    0    0   0    0    0    0    0    0    0  ...    0    0    0    0   
26   34    6   36  10   20   10   43   30    8   18  ...   44   20   39   22   
27   12    0    0   1    0    0   22    6    0    8  ...    0    0   10    4   
28    0    0    0   0    0    0    0    0    0    0  ...    0    0    0    0   
29    0    0    0   0    0    0    0    0    0    0  ...    0    0    0    0   
30    0    0    0   0    0    0    0    0    0    0  ...    0    0    0    0   
31    2    0    0  14    0    0   10   13    0    7  ...    0   25   12    5   
32    1    0    0   1    0    0    2    1    0    0  ...    0    0    3    0   
33    3    0    0   0    0    0    6    8    0    3  ...    0    7    3    0   
34    2    0    0   3    0    0    2    3    0    0  ...    0    2    0    0   
35    1    0    0   2    0    0    2    6    0    0  ...    0    5    2    2   
36    1    0    0   6    0    0    0    4    0    0  ...    0    4    1    0   
37    0    0    0   0    0    0    7    2    0    1  ...    0    1    4    0   
38    0    0    0   0    0    0    0    0    0    0  ...  227    0    0    0   
39    0    0    0  12    0    0    0   13    0    3  ...    0  181    5    1   
40    8    0    0   1    0    0   13    3    0    6  ...    0    1  229    1   
41    2    0    0   1    0    0    2    4    0    0  ...    0    3    5  122   
42    0    0    0   7    0    0    0   12    0    0  ...    0   12    3    0   
43    0    0    0   0    0    6    0    0    0    0  ...    0    0    0    0   
44    0    0    0   0    0    0    0    0    0    0  ...    0    0    0    0   
45    0    0    0   0    0    0    0    0    0    0  ...    0    0    0    0   
46    0    0    0   0    0    0    0    0    0    0  ...    0    0    0    0   
47    0    0    0   0    0    0    0    0    0    0  ...    0    0    0    0   

     42   43   44  45   46   47  
0     1    0    0   0    0    0  
1     0    0    

Accuracy Score : 0.8104610898487333
Classification Report
              precision    recall  f1-score   support

           0       0.53      0.56      0.54       219
           1       0.98      1.00      0.99       241
           2       0.74      0.87      0.80       118
           3       0.50      0.53      0.51       127
           4       0.90      0.91      0.90       190
           5       0.93      0.92      0.92       258
           6       0.72      0.74      0.73       683
           7       0.55      0.62      0.58       284
           8       0.93      0.96      0.95       109
           9       0.59      0.59      0.59       175
          10       0.69      0.71      0.70       107
          11       1.00      0.99      0.99       201
          12       0.74      0.72      0.73       180
          13       0.79      0.74      0.77       956
          14       0.82      0.84      0.83       116
          15       0.60      0.61      0.61       281
          16       0.54